-- CALCULO NAS COLUNAS --
-- Round - É UMA FUNÇÃO DO ORACLE QUE ARREDONDA O NUMERO DE CASOS DECIMAIS, VOCE COLOCA A CONTA DENTRO DO PARENTESES E DEPOIS DA VIRGULA SE INFORMA O NUMERO DE CASAS DECIMAIS --
SELECT NOME AS CURSO, VALOR, VALOR/CARGA_HORARIA, Round(VALOR/CARGA_HORARIA, 2) AS VALOR_HORA
FROM C_CURSO
ORDER BY VALOR_HORA;

-- SELECT BÁSICO NA TABELA C_CONTRATO --
SELECT * FROM C_CONTRATO;

-- UPDATE NA TABELA C_CONTRATO --
-- VAI ATUALIZAR A COLUNA DESCONTO DO REGISTRO 4 PRA NULO --
UPDATE C_CONTRATO
SET DESCONTO = NULL
WHERE COD_ALUNO = 4;

-- FAZER CONTA COM NULOS SIMPLISMENTE ANULA O RESULTADO --
SELECT COD_CONTRATO, TOTAL, DESCONTO, (TOTAL - DESCONTO) FROM C_CONTRATO;

-- A FUNÇÃO Mvl() SERVE PRA TRATAR FUNÇÕES NULAS, PRIMEIRO SE INFORMA A COLUNA QUE DEVE SER TRATADA E DEPOIS DA VÍRGULA É INSERIDO O DADO QUE SE DEJESA APRESENTAR NO LUGAR DO NULO --
-- ENTÃO EM CASOS ONDE É UMA POSSÍBILIDADE QUE UMA COLUNA SEJA NULA É SEMPRE BOM USAR O 'NVL'
SELECT COD_CONTRATO, TOTAL, Nvl(DESCONTO, 0) FROM C_CONTRATO;

-- CONCATENAÇÃO --
SELECT COD_ALUNO || ' - '|| NOME || ' // ' || CIDADE AS ALUNO FROM C_ALUNO ORDER BY COD_ALUNO;

-- ADIÇÃO DE COLUNAS --
-- QUANDO SE INSERE UMA COLUNA NOVA DEPOIS QUE A TABELA JÁ ESTÁ POPULADA O FAZ COM QUE TODOS OS REGISTROS TENHA DE INICIO O DADO INFORMADO NELE --
ALTER TABLE C_ALUNO ADD ESTADO CHAR(2) DEFAULT 'RS';
ALTER TABLE C_ALUNO ADD SALARIO NUMBER( 8,2) DEFAULT 620;

SELECT * FROM C_ALUNO;

-- UPDATE --
UPDATE C_ALUNO SET
ESTADO = 'MT', SALARIO = 800
WHERE COD_ALUNO = 2;

UPDATE C_ALUNO SET
ESTADO = 'SP', SALARIO = 800
WHERE COD_ALUNO = 4;

COMMIT;

SELECT * FROM C_ALUNO
WHERE ESTADO <> 'RS'
AND SALARIO <= 800
ORDER BY SALARIO DESC;

DROP SEQUENCE SEQ_ALUNO;

CREATE SEQUENCE SEQ_ALUNO START WITH 1;

-- ORDENAÇÃO --
SELECT ESTADO, SALARIO, NOME FROM C_ALUNO ORDER BY ESTADO, SALARIO DESC;

-- ADICAO DE COLUNA COM DATA --
ALTER TABLE C_ALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE;

-- SELECIONA A DATA ATUAL DO SISTEMA --
SELECT SYSDATE FROM DUAL;

-- SELECIONA A DATA ATUAL MENOS 100 DIAS --
SELECT (SYSDATE - 100) FROM DUAL;

-- UPDATES NOVOS --
UPDATE C_ALUNO SET
NASCIMENTO = '10/10/2001'
WHERE COD_ALUNO = 1;

UPDATE C_ALUNO SET
NASCIMENTO = '10/08/2000'
WHERE COD_ALUNO = 2;

SELECT * FROM C_ALUNO;

-- Trunc() É UMA FUNÇÃO QUE SERVE PARA TIRAR A HORA DE CAMPOS DE DATA -- 
SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO), NOME
FROM C_ALUNO
WHERE Trunc(NASCIMENTO) = '09/04/2018';

-- PEGAR UMA DATA QUE ESTEJA ENTRE DETERMINADO PERIODO --
SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO) AS NASCIMENTO, NOME
FROM C_ALUNO
WHERE NASCIMENTO
BETWEEN TO_DATE('25/08/2010 22:00', 'DD/MM/YYYY HH24:MI')-- O PRIMAEIRO FORMATO É A HORA A SER FILTRADA E O ULTIMO FORMATO DE HORA É O FORMATO A SER CONSIDERADO NA HORA DE FAZER A CONSULTA --
AND TO_DATE('10/04/2018 23:55', 'DD/MM/YYYY HH24:MI');
